version: '3.7'

services:
  api:
    build: .
    container_name: app
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
