apiVersion: v1
kind: Service

metadata:
  name: api-infra-learnings-service
  labels:
    app: api-infra-learnings

spec:
  selector:
    app: api-infra-learnings
  type: ClusterIP
  ports:
    - name: api-infra-learnings-service-port
      protocol: TCP
      port: 80
      targetPort: 3000
